service: serverless

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-2
  environment:
    MONGO_URI: ${file(./serverless.env.yml):dev.MONGO_URI}
    LIST_SIZE: 6
    
functions:
  writePost:
    handler: src/api/post.writePost
    events:
      - http:
          path: posts
          method: post
  readPostList:
    handler: src/api/post.readPostList
    events:
      - http:
          path: posts
          method: get
  updatePost:
    handler: src/api/post.updatePost
    events:
      - http:
          path: posts/{id}
          method: patch
  deletePost:
    handler: src/api/post.deletePost
    events:
      - http:
          path: posts/{id}
          method: delete

plugins:
  - serverless-offline